name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cp-tracker-be
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev
          docker build -t ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cp-tracker/cp-tracker-be:latest .
          docker push ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cp-tracker/cp-tracker-be:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cp-tracker-be \
            --image=${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cp-tracker/cp-tracker-be:latest \
            --region=${{ secrets.GCP_RUN_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=ALLOW_ORIGINS=${{ vars.GO_ALLOW_ORIGINS }},JWT_SECRET=${{ secrets.GO_JWT_SECRET }},MONGO_URI=${{ secrets.GO_MONGO_URI }}
